#! /bin/bash

#kill previous session
#pkill compton

sxhkd &
~/.config/polybar/launch.sh &
#xfce4-panel &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
compton -b --config ~/.config/compton/compton.conf &
#nitrogen --restore &
~/.fehbg &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
clipit &
pasystray &
nm-applet &
blueman-applet &
mpd &
udiskie &
pamac-tray &
guake &
xautolock -time 10 -locker '~/.bin/glitch.sh' &
wal -R &
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3

bspc config border_width         5
bspc config window_gap          35

bspc config split_ratio           0.5
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focused_border_color "$color1"
bspc config active_border_color  "$color1"
bspc config normal_border_color  "$color0"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true
bspc config border_radius         10
#bspc config top_padding           30


bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nm-connection-editor state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a Guake state=floating
bspc rule -a Xarchiver state=pseudo_tiled
bspc rule -a Eog state=floating
bspc rule -a "Kvantum Manager" state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gpick state=floating
bspc rule -a Dconf-editor state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Steam state=floating follow=on
bspc rule -a '*:xfce4-panel' state=floating
bspc rule -a File-roller state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating

alacritty -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating hidden=on

#bspc rule -a scratchpad sticky=on state=floating hidden=on
#kitty -c scratchpad -e ~/bin/scratch &





